### ISSUE TITLE
Why does the schema resource only return sites and not histologies?

### ISSUE THREAD

**Issue by mgurley** [imsweb/seerapi-client-java#17]
The SEER API appears to only return sites for a schema resource.  See this call:

https://api.seer.cancer.gov/rest/staging/tnm/latest/schema/prostate

This returns the following:

{
  "id": "prostate",
  "algorithm": "tnm",
  "version": "1.9",
  "name": "Prostate",
  "title": "Prostate",
  "notes": "C619  Prostate gland\n\n**Note 1:** This schema is based on the UICC chapter *Prostate* pages 243-248.\n\n**Note 2:** Transitional cell (urothelial) carcinoma of the prostatic urethra is to be coded to primary site C680, Urethra, and TNM assigned according to the Urethra schema.\n\n**Note 3:** The 7th Edition TNM stage groups are derived from T, N, M, PSA and Gleason Score. The following SSF's are used for PSA and Gleason Score. \n* SSF 1: Prostatic Specific Antigen (PSA) Lab Value\n* SSF 8: Gleason's Score on Needle Core Biopsy/Transurethral Resection of Prostate (TURP) (Clinical Stage Group)\n* SSF 10: Gleason's Score on Prostatectomy/Autopsy (Pathologic Stage Group)\n\n**Note 4:** In addition to directly assigning TNM, Summary Stage 2000 (SS2000) must be captured.  If directly assigning SS2000, use the *Prostate* chapter on page 230 of the [SS2000 on-line manual](https://seer.cancer.gov/tools/ssm/ssm2000/SSSM2000-122012.pdf#page=230).",...

It seems that this schema resource only defines the schema in terms of sites.  Not histologies.  However, the staging.seer.cancer.gov website seems to define schemas in terms of sites **and** histologies.  See here:
https://staging.seer.cancer.gov/tnm/schema/1.9/prostate/?breadcrumbs=(~schema_list~)

Why does the SEER APi not return a list of histologies for a schema?

**Comment by ctmay4** [comment]
This call is designed to return a single schema by schema_id.

https://api.seer.cancer.gov/rest/staging/tnm/latest/schema/prostate

One of the elements in the schema is `schema_selection_table`.  For "prostate" it is defined as `schema_selection_prostate`.  That is the table name that handles schema selection and it lists all the site/hist combinations that make up the schema (and if necessary, the discriminator as well).

```json
{
  "id": "schema_selection_prostate",
  "algorithm": "tnm",
  "version": "1.9",
  "name": "Schema Selection Prostate",
  "title": "Schema selection for Prostate",
  "last_modified": "2018-05-14T21:29:00.044Z",
  "definition": [
    {
      "key": "site",
      "name": "Primary Site",
      "type": "INPUT"
    },
    {
      "key": "hist",
      "name": "Histology",
      "type": "INPUT"
    },
    {
      "key": "result",
      "name": "Result",
      "type": "ENDPOINT"
    }
  ],
  "rows": [
    [
      "C619",
      "8000-9136,9141-9582,9700-9701",
      "MATCH"
    ]
  ]
}
```

If you want to find a schema by site and histology, you should use the lookup API.  For example:

POST /rest/staging/tnm/latest/schemas/lookup

with post data 

```json
{
    "site": "C619",
    "hist": "9582"
}
```

returns:

```json
[
  {
    "id": "prostate",
    "name": "Prostate",
    "title": "Prostate",
    "staging_inputs": [
      "site",
      "hist"
    ],
    "staging_outputs": [
      "combined_m",
      "combined_n",
      "source_t",
      "derived_version",
      "clin_stage_group",
      "combined_t",
      "combined_stage_group",
      "path_stage_group",
      "source_n",
      "source_m"
    ]
  }
]
```

There is more documentation on schema lookup here:

https://github.com/imsweb/staging-client-java/wiki/lookupSchema

Does that answer your question?

**Comment by mgurley** [comment]
Great, now I understand.  Thanks for the answer.
