### ISSUE TITLE
Why does the NAACCR field resource not return the "Section" of a NAACCR field?

### ISSUE THREAD

**Issue by mgurley** [imsweb/seerapi-client-java#18]
The SEER API appears to not return the "Section" that a NAACCR field belongs to?  See this call:

https://api.seer.cancer.gov/rest/naaccr/latest/item/1290

This returns the following:

```
{
  "item": 1290,
  "name": "RX Summ--Surg Prim Site",
  "start_col": 2225,
  "end_col": 2226,
  "alignment": "RIGHT",
  "padding_char": "0",
  "documentation": "<table class=\"naaccr-summary-table naaccr-borders\">\n    <tr>\n        <th class=\"naaccr-summary-header naaccr-borders\">Item #</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Length</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Source of Standard</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Year Implemented</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Version Implemented</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Year Retired</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Version Retired</th>\n        <th class=\"naaccr-summary-header naaccr-borders\">Column #</th>\n    </tr>\n    <tr>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\">1290</td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\">2</td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\">SEER/CoC</td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\">1997</td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\">5.1</td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\"></td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\"></td>\n        <td class=\"naaccr-summary-cell naaccr-borders naaccr-summary-centered\">2225 - 2226</td>\n    </tr>\n</table>\n\n<br/><strong>NAACCR XML</strong>: Tumor.rxSummSurgPrimSite<br/><br/>\n<strong>Alternate Names</strong>\n<br/>&nbsp;&nbsp;&nbsp;Surgery of Primary Site (SEER/CoC)\n<br/>&nbsp;&nbsp;&nbsp;Cancer-Directed Surgery (pre-96 CoC)\n\n\n<div class='content chap10-para-head'><strong><strong>Description</strong></strong></div>\n<div class='content chap10-para mark-changed'>Site-specific codes for the type of surgery to the primary site performed as part of the first course of treatment. This includes treatment given at all facilities as part of the first course of treatment.</div>\n<div class='content chap10-para mark-changed'><strong>Codes (in addition to the site-specific codes; Refer to the most recent version of\n    <em>STORE</em> and SEER Program Code manual for additional instructions.) </strong></div>\n<div class='content chap10-para'>\n    <table>\n        <tr class='code-row'>\n            <td class='code-nbr'>00</td>\n            <td class='code-desc'>None</td>\n        </tr>\n        <tr class='code-row'>\n            <td class='code-nbr'>10-19</td>\n            <td class='code-desc'>Site-specific code; tumor destruction</td>\n        </tr>\n        <tr class='code-row'>\n            <td class='code-nbr'>20-80</td>\n            <td class='code-desc'>Site-specific codes; resection</td>\n        </tr>\n        <tr class='code-row'>\n            <td class='code-nbr'>90</td>\n            <td class='code-desc'>Surgery, NOS</td>\n        </tr>\n        <tr class='code-row'>\n            <td class='code-nbr'>98</td>\n            <td class='code-desc'>Site specific codes; special</td>\n        </tr>\n        <tr class='code-row'>\n            <td class='code-nbr'>99</td>\n            <td class='code-desc'>Unknown</td>\n        </tr>\n    </table>\n</div>"
}
```
It seems that  NAACCR item resource omits "Section" information.   Alternatively, the "Section" of NAACCR itmes is available via download from the NAACCR 'Data Standards and Data Dictionary – Query Builder' (NAACCR Query Builder) application at the following location:

http://applications.naaccr.org/querybuilder/default.aspx?Version=18

For example NAACCR #1290  is presented within the 'Treatment-1st Course' section from the NAACCR Query Builder application. 

Why does the SEER API not return the "Section" information?  Sections are very useful for the organization of NAACCR variables.

Cancer   Identification
Demographic
Edit Overrides/Conversion History/System   Admin
Follow-up/Recurrence/Death
Hospital-Confidential
Hospital-Specific
Other-Confidential
Pathology
Patient-Confidential
Record ID
Special Use
Stage/Prognostic Factors
Text-Diagnosis
Text-Miscellaneous
Text-Treatment
Treatment-1st Course
Treatment-Subsequent & Other

I see that "Sections" are also not present within the NAACCR XML format.  See here: https://github.com/imsweb/naaccr-xml.  

Are NAACCR "Sections" obsolete and decprecated?

**Comment by ctmay4** [comment]
I'm not sure what you are talking about here.  It also sounds similar to the question you asked last week in #17.

**Comment by mgurley** [comment]
@ctmay4 Sorry my question has been updated.  Let me know if makes sense.

**Comment by ctmay4** [comment]
NAACCR "sections" are not deprecated, but keep in mind that the official supposed format starting in 2020 is NAACCR XML.  The NAACCR XML definitions do not currently support a section definition.  Of couse that may change, I'm not sure.

We actually do have access to the section for flat file.  I think its omission in the API was just an oversight.  I will add it to the endpoint and do a release of SEER*API (and the client) in the next week or so.

**Comment by mgurley** [comment]
@ctmay4 Thanks so much for the response.  And the upcoming change to the API.  Do you know who/where I should petition to get "Sections" added to NAACCR XML?

**Comment by ctmay4** [comment]
I'm not involved in the XML process, but there is a forum.  I think you can post your request there.

https://www.naaccr.org/forums/forum/naaccr-xml-standard/

**Comment by ctmay4** [comment]
SEER*API was updated this morning.  If you update to the latest version of seerapi-client-java (3.14) you will get section information included now.

**Comment by mgurley** [comment]
See it!  Again, thanks so much.
