### ISSUE TITLE
Why does the NAACCR version resource not retrun NAACCR item 780 for latest/version 18?

### ISSUE THREAD

**Issue by mgurley** [imsweb/seerapi-client-java#20]
A call to the following resource does not include NAACCR #780:

https://api.seer.cancer.gov/rest/naaccr/18

Though NAACCR #780 seems to be part of the latest/version 18.  See here:

http://datadictionary.naaccr.org/default.aspx?c=10#780

**Comment by mgurley** [comment]
Ditto for NAACCR #800.

**Comment by mgurley** [comment]
Ditto for NAACCR #820 http://datadictionary.naaccr.org/default.aspx?c=10#820

**Comment by mgurley** [comment]
Ditto for NAACCR #830 http://datadictionary.naaccr.org/default.aspx?c=10#830

**Comment by ctmay4** [comment]
This is being looked at in https://github.com/imsweb/layout/issues/64.  Once that library is fixed I will update SEER*API.

**Comment by ctmay4** [comment]
This is an oversight in SEER*API and doesn't have to do with the layout library.  I will fix this and release SEER*API soon.

**Comment by ctmay4** [comment]
SEER*API was updated and this bug has been fixed.
