### ISSUE TITLE
The recently added section information to the NAACCR field resource is wrong for some fields.

### ISSUE THREAD

**Issue by mgurley** [imsweb/seerapi-client-java#21]
It seems like many NAACCR fields in the 'Treatment-1st Course' section are reported as being in the "Stage/Prognostic Factors' section.  For example:

https://api.seer.cancer.gov/rest/naaccr/latest/item/1512

See here for what seems to be uniformly correct:

http://datadictionary.naaccr.org/default.aspx?c=7

**Comment by ctmay4** [comment]
SEER*API makes use of another library to provide the NAACCR documentation.  

https://github.com/imsweb/layout

I am going to submit this issue in that project and see what the problem is.  Once the library is fixed I will update the API and the library should return correct results.

**Comment by ctmay4** [comment]
The layout library was updated and I just rolled the fixes into SEER*API.  The section values should all be correct now.
