### ISSUE TITLE
How to get subjects data?

### ISSUE THREAD

**Issue by yangxxxi2** [imsweb/seerapi-client-java#33]
I am interested in seer-api and have studied its document carefully. I have tried to use seer-api extracting data, but I can only get the data of the data structure, I cannot get patients' data like seer-stat. I am wondering if you could kindly send me some tips about seer-spi to get data like seer-stat. I promise data will be used only for research.Thank you for your kind consideration and I am looking forward to your reply.

**Comment by ctmay4** [comment]
SEER*API has nothing to do with SEER Stat.  There is no patient data stored in SEER*API.  If you need support for SEER*Stat, please use this link:

https://seer.cancer.gov/registrars/contact.html

**Comment by yangxxxi2** [comment]
Very thanks for your reply！And I want to know if I can get data from SEER incidence database by using SEER api？

**Comment by ctmay4** [comment]
No you cannot.  As I mentioned SEER*API has no relation to SEER\*Stat.  The SEER incidence database is only in SEER\*Stat.
